# Generated by Django 4.2.2 on 2023-06-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SUN', 'Sunny'), ('CLO', 'Cloudy'), ('WIN', 'Windy'), ('RAI', 'Rainy'), ('STO', 'Stormy')], max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
