# Generated by Django 4.2.2 on 2023-06-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('SUN', 'Sunny'), ('CLO', 'Cloudy'), ('WIN', 'Windy'), ('RAI', 'Rainy'), ('STO', 'Stormy')], max_length=3),
        ),
    ]
