# Generated by Django 4.2.2 on 2023-06-17 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='custom_id',
        ),
    ]
